### ISSUE TITLE
777 

### ISSUE THREAD

**Issue by Eldo420** [malaysia-ai/jupyter-gpu#38]
Baiklah, saya akan menulis panduan terperinci dalam Bahasa Malaysia tentang cara menyediakan Jupyter Notebook dengan sokongan GPU dan Code Server. Ini akan berguna terutamanya untuk pelajar yang berminat dalam pembelajaran AI dan pembelajaran mesin yang memerlukan kecekapan GPU.

---

## Jupyter-GPU: Jupyter Notebook dengan GPU dan Code Server

Projek **Jupyter-GPU** direka untuk menyediakan persekitaran Jupyter Notebook yang boleh memanfaatkan GPU untuk mempercepatkan latihan model AI. Ia juga termasuk Code Server untuk perkembangan kod yang lebih efisien. Berikut adalah panduan langkah demi langkah untuk memasang dan menggunakan Jupyter-GPU.

### Prasyarat
Sebelum anda memulakan, pastikan anda mempunyai perkara berikut:
1. **Akun GitHub:** Jika anda masih belum mempunyai akaun GitHub, anda boleh mendaftar [di sini](https://github.com/).
2. **Docker:** Pastikan Docker telah dipasang pada komputer anda. Anda boleh muat turun dan pasang Docker dari [laman rasmi Docker](https://www.docker.com/products/docker-desktop). (Nota: Docker memerlukan sistem 64-bit dan ciri virtualisasi yang diaktifkan di BIOS).
3. **NVIDIA Docker:** Ini diperlukan jika anda ingin menggunakan GPU NVIDIA. Anda boleh rujuk dokumentasi rasmi NVIDIA untuk panduan pemasangan [di sini](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html).

#### Langkah 1: Fork dan Clone Projek
1. **Fork Repositori:** Pergi ke repositori [Jupyter-GPU](https://github.com/malaysia-ai/jupyter-gpu) di GitHub dan klik butang "Fork" untuk menyalin repositori ke akaun GitHub anda.

2. **Clone Repositori:** Selepas fork, clone repositori ke peranti anda menggunakan Git.
   ```sh
   git clone https://github.com/username/jupyter-gpu.git
   ```

#### Langkah 2: Mula Kontena Docker
1. **Navigasi Ke Direktori Projek:**
   ```sh
   cd jupyter-gpu
   ```

2. **Membangunkan dan Melancarkan Kontena:**
   Gunakan docker-compose untuk membangunkan dan melancarkan kontena. Ini akan mencipta persekitaran Jupyter Notebook yang mempunyai sokongan GPU serta Code Server.
   ```sh
   docker-compose up --build
   ```

#### Langkah 3: Akses Jupyter Notebook
1. **Nota Token Akses:**
   Selepas kontena dilancarkan, `docker-compose` akan memberikan anda token Jupyter Notebook di terminal. Token ini diperlukan untuk log masuk.
   ```sh
   ⠿ Container jupyter-gpu  Started
   ...
   Copy/paste this URL into your browser when you connect for the first time,
   to login with a token:
       http://127.0.0.1:8888/?token=YOUR_TOKEN_HERE
   ```

2. **Buka Pelayar dan Akses:**
   Buka pelayar web dan akses Jupyter Notebook dengan URL yang disediakan, termasuk token.
   ```sh
   http://127.0.0.1:8888/?token=YOUR_TOKEN_HERE
   ```

#### Langkah 4: Akses Code Server
1. **Akses Code Server:**
   Untuk menggunakan Code Server, akses melalui pelayar web pada URL yang berbeza. (Nota: Port boleh dikonfigurasi dalam `docker-compose.yaml`)
   ```sh
   http://127.0.0.1:8080
   ```

2. **Login dan Gunakan:**
   Log masuk menggunakan kelayakan default atau kelayakan yang telah anda atur semasa konfigurasi
   ```sh
   Username: admin
   Password: admin (atau kata laluan yang telah anda tetapkan)
   ```

#### Langkah 5: Penggunaan GPU di Jupyter Notebook
Untuk memastikan Jupyter Notebook anda menggunakan GPU, anda boleh mengimport perpustakaan seperti TensorFlow dan memeriksa sama ada GPU terdeteksi.
```python
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

### Tips dan Sumber Tambahan
- **Dokumentasi Docker:** Biasakan diri anda dengan kemahiran asas Docker dengan merujuk [dokumentasi Docker](https://docs.docker.com/).
- **Belajar Jupyter:** Untuk pemahaman mendalam tentang Jupyter Notebook, anda boleh merujuk [dokumentasi rasmi Jupyter](https://jupyter.org/documentation).
- **Tutorial Pembelajaran Mesin:** Banyak tutorial dan panduan pemula untuk pembelajaran mesin boleh didapati di platform seperti Coursera, Udacity, dan YouTube.

#### Adakah saya memerlukan GPU untuk menggunakan projek ini?
Walaupun GPU tidak wajib, ia sangat disyorkan untuk mempercepatkan latihan model AI.

#### Bagaimana saya boleh menambah lebih banyak extensions dalam Jupyter Notebook?
Anda boleh memasang extensions melalui Jupyter Terminal atau konfigurasi Dockerfile yang disertakan dalam repositori ini.

#### Bagaimana saya menyumbang kepada projek ini?
Sila buat cawangan baru, lakukan perubahan anda dan minta 'pull request' (PR). Pihak pengurus projek akan menyemak dan meluluskan PR anda jika sesuai.

Terima kasih kerana menggunakan **Jupyter-GPU**! Kami berharap panduan ini membantu anda memulakan perjalanan anda dalam AI dengan lebih mudah dan efisien.

---

**Comment by aisyahrzk** [comment]
spam

**Comment by Eldo420** [comment]
Read more kid...

**Comment by Eldo420** [comment]
Thanks, I will!
